project_id = "nxzlqkbqspygvfnahixo"

[functions.generate-proposal]
verify_jwt = false

[functions.generate-mockup]
verify_jwt = false

[functions.paddle-webhook]
verify_jwt = false

[functions.cancel-subscription]
verify_jwt = false

[functions.generate-cover-letter]
verify_jwt = false

[functions.generate-email]
verify_jwt = false